### PR TITLE
Add travis.yml

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

https://travis-ci.org/gliptak/downloadstar/builds/474143439

### CODE REVIEW

**Comment by gliptak** [comment]
@marklieberman please review

**Comment by marklieberman** [comment]
Thank you

**Comment by gliptak** [comment]
@marklieberman please enable builds for your repo at https://travis-ci.org/marklieberman/downloadstar/

**Comment by marklieberman** [comment]
@gliptak I have activated the repo on travis.

**Pull request merged**
